SELECT OO1.ID AS ORDER_ID,
OO2.ID AS DESADV_ID,
OO2.CREATEDATE AS DESADV_CREATE_DATE,
FROM ORTORDER OO1, ORTORDER OO2, ORTORDERPARTY OP
WHERE OO1.ORDERDID = OO2.PARENTORDERDID
AND OO1.ORDERDID = OP.ORDERDID
AND OO2.ORDERCATEGORYDID = 9
AND OP.ORDERPARTYTYPEDID = 4
AND OP.ISWAREHOUSE = 1
AND OO2.CREATEDATE >= TRUNC (SYSDATE - 1)
AND OO2.CREATEDATE < TRUNC (SYSDATE)
ORDER BY OO1.ID, OO2.ID