SELECT OO.ID,
OS.RESPONSEID,
OP.EANNO,
OP.NAME,
FROM ORTORDERRESPONSE OS, ORTORDER OO, ORTORDERPARTY OP
WHERE 1 = 1
AND OS.ORDERREFERENCE = OO.ID
AND OO.ORDERDID = OP.ORDERDID
AND OP.ORDERPARTYTYPEDID = 4
AND OP.ISWAREHOUSE = 1
AND OS.RESPONSEDATE >= TRUNC (SYSDATE - 1)
AND OS.RESPONSEDATE < TRUNC (SYSDATE)
ORDER BY OO.ID, OS.RESPONSEDATE